openapi: 3.0.0
info:
  title: Smart Home API
  version: 1.0.0
  description: API for managing devices and telemetry in a smart home system.

paths:
  /devices/{device_id}:
    get:
      summary: Get Device Information
      description: Returns detailed information about a specific device by its ID.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  type:
                    type: string
                  status:
                    type: string
                  serial_number:
                    type: string
        '404':
          description: Device not found
        '500':
          description: Server error

  /devices/{device_id}/status:
    put:
      summary: Update Device Status
      description: Allows changing the device status (e.g., turn on/off).
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
      responses:
        '200':
          description: Status updated successfully
        '400':
          description: Bad request
        '404':
          description: Device not found
        '500':
          description: Server error

  /devices/{device_id}/commands:
    post:
      summary: Send Command to Device
      description: Sends a command to the device (e.g., "set temperature to 22 degrees").
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                command:
                  type: string
                parameters:
                  type: object
                  additionalProperties: true
      responses:
        '200':
          description: Command sent successfully
        '400':
          description: Bad request
        '404':
          description: Device not found
        '500':
          description: Server error

  /devices/{device_id}/telemetry/latest:
    get:
      summary: Get Latest Telemetry Data
      description: Returns the latest telemetry data for the device.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  timestamp:
                    type: string
                  data:
                    type: object
                    additionalProperties: true
        '404':
          description: Device not found
        '500':
          description: Server error

  /devices/{device_id}/telemetry:
    get:
      summary: Get Historical Telemetry Data
      description: Returns historical telemetry data for the device over a specified period.
      parameters:
        - name: device_id
          in: path
          required: true
          schema:
            type: string
        - name: start_date
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: end_date
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: string
                    data:
                      type: object
                      additionalProperties: true
        '400':
          description: Bad request
        '404':
          description: Device not found
        '500':
          description: Server error